### ISSUE TITLE
F E A T U R E | Basic Rest API

### ISSUE THREAD

**Issue by LemMem** [LemMem/horizon#1]
**Is your feature request related to a problem? Please describe.**
If you consider us having no fucking code a problem then yes. We have no fucking code.

**Describe the solution you'd like**
The Elixir API should be written in [Plug](https://hexdocs.pm/plug/readme.html), we don't want anything to heavy-duty, something like [Phoenix ](https://www.phoenixframework.org/)would be a little overkill.

**Describe alternatives you've considered**
We could use an alternative systems language, like [Node](https://nodejs.org/), [Deno](https://deno.land/), or [Rust](https://www.rust-lang.org/). From my research, Elixir would provide the best experience for development. Plus we have to much Typescript in this project already.

**TODO**

- [x] Post Data to Web
- [x] Allow Different paths for API
- [x] Allow Dynamic paths
- [x] Setup proper commands (see solstice readme)
